# Puerto de la aplicación
server.port=8080

# Base de datos PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://db.hoqljvonhcozhuetchmv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=JosTovAzp.120497
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf (para las páginas HTML)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Subida de archivos (para las fotos)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Ruta para guardar fotos
app.upload.dir=